# basic site info
site_name: Coronal Hole Detection Project
site_description: Python routines and documentation for the PSI Coronal Hole Detection Project.
site_author: Tamar Ervin
site_favicon: img/favicon.ico

# repository information
repo_url: https://github.com/predsci/CHD
edit_uri: blob/master/CHD-mkdocs/docs/

# site navigation
nav:
  - Home: index.md
  - About the Project: about.md
  - Image Pre-Processing:
      - PSF Deconvolution: ipp/psf.md
      - Limb-Brightening Correction: ipp/lbc.md
      - Inter-Instrument Transformation: ipp/iit.md
  - Database:
      - Database Basics: db/db.md
      - Database for LBC: db/lbc.md
      - Database for IIT: db/iit.md

# theme
theme:
  name: material
  language: en
  palette:
    primary: indigo
    accent: black
  logo: img/logo.png



# plugins
plugins:
  - search:
      lang: en

# extensions
markdown_extensions:
  - attr_list
  - codehilite:
      linenums: true
