# basic site info
site_name: Coronal Hole Detection Project
site_description: Python routines and documentation for the PSI Coronal Hole Detection Project.
site_author: Tamar Ervin

# repository information
repo_url: https://github.com/predsci/CHD

# site navigation
nav:
  - Home: index.md
  - About the Project: about.md
  - Image Pre-Processing:
      - PSF Deconvolution: ipp/psf.md
      - Limb-Brightening Correction: ipp/lbc.md
      - Inter-Instrument Transformation: ipp/iit.md
  - Database:
      - Database Basics: db/db.md
      - Database for LBC: db/lbc.md

# theme
theme:
  name: readthedocs
  language: en
  palette:
    primary: black
    accent: blue

# plugins
plugins:
  - search:
      lang: en

# extensions
markdown_extensions:
  - attr_list
  - codehilite:
      linenums: true
