# basic site info
site_name: Coronal Hole Detection Project
site_description: Python routines and documentation for the PSI Coronal Hole Detection Project.
site_author: Tamar Ervin

# repository information
repo_url: https://github.com/predsci/CHD
edit_uri: blob/master/CHD-mkdocs/docs/

# site navigation
nav:
  - Home: index.md
  - About the Project: about.md
  - Image Pre-Processing:
      - PSF Deconvolution: ipp/psf.md
      - Limb-Brightening Correction: ipp/lbc.md
      - Inter-Instrument Transformation: ipp/iit.md
  - Coronal Hole Detection:
      - Fortran to Python: chd/f2py.md
      - CH Detection: chd/chd.md
  - Mapping:
      - Mapping Pipeline: map/map.md
      - Interpolation: map/int.md
      - Combining Maps: map/cmb.md
  - Data Products:
      - Synoptic Maps: dp/cr.md
      - Quality Maps: dp/qm.md
      - Ensemble Detection: dp/ed.md
      - Varying Threshold Maps: dp/vt.md
  - Database:
      - Database Basics: db/db.md
      - Database for LBC: db/lbc.md
      - Database for IIT: db/iit.md
      - Database for CHD Mapping: db/map.md
  - Tracking Algorithm:
      - Overview: ml/tracking_overview.md
      - Polar Projection: ml/polarprojection.md
      - Latitude Weighted Dilation: ml/latitude_weighted_dilation.md
      - CH Features: ml/tracking_features.md
      - CH Frame Matching:
          - Overview: ml/match_overview.md
          - KNN: ml/knn.md
          - Area Overlap: ml/areaoverlap.md
      - CH Connectivity: ml/connectivity.md

  - Machine Learning Detection: ml/chd.md
  - CH-Net Future Frame Predictions: ml/pred.md

# theme
theme:
  name: material
  language: en
  palette:
    primary: indigo
    accent: black
  logo: img/psi_logo.png

# plugins
plugins:
  - search:
      lang: en

# extensions
markdown_extensions:
  - attr_list
  - codehilite:
      linenums: true
  - admonition
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.arithmatex


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
