name: chd
channels:
  - defaults
  - conda-forge
dependencies:
  - alembic
  - astropy < 4.2
  - drms
  - h5py
  - matplotlib
  - mysqlclient
  - numpy
  - pyhdf
  - python >= 3.7
  - scipy
  - sqlalchemy-utils
  - sunpy == 1.1.2
  - opencv >= 3.4
  - scikit-learn >= 0.24
  - networkx >= 2.5
  - notebook