name: chmap
channels:
  - defaults
  - conda-forge
dependencies:
  - alembic
  - astropy
  - drms
  - h5py
  - matplotlib
  - mysqlclient
  - numpy
  - pyhdf
  - python >= 3.7
  - scipy
  - sqlalchemy-utils
  - sunpy
  - opencv >= 3.4
  - scikit-learn >= 0.24
  - networkx >= 2.5
  - notebook
  - mkdocs-material
  - mkdocs-jupyter
