name: chd
channels:
  - defaults
  - conda-forge
dependencies:
  - alembic
  - astropy-healpix
  - drms
  - h5py
  - matplotlib
  - mysqlclient
  - numpy
  - pyhdf
  - python=3.7
  - scipy
  - sqlalchemy-utils
  - sunpy=1.1.2
  - opencv>=4.5.1.48
  - scikit-learn>=0.24.1
  - networkx>=2.5
